---
title: "Developing Data Products - Week 2 Project"
author: "Bo Suzow"
date: "January 4, 2018"
output: html_document
---

##Map featuring certificate (in red) or associate's degree (in blue) institutions in Southern California.

####Click on circles to see the clickable names and completion rates ([data source: The College Scorecard for the 2015-16 year](https://collegescorecard.ed.gov/data/)).

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r dataload, include=FALSE}

# MERGED2015_16_CA_JC.csv is a subset of MERGED2015_16_PP.csv downloaded 
# from https://collegescorecard.ed.gov/data/ filtered on the following criteria:
#        ST = "CA" & PREDDEG = 1 or 2 (certificate or associate's degree institutions)

scCAJC = read.csv("MERGED2015_16_CA_JC.csv",na.strings="NULL")

# Filtered out certificate institutions.  This removes LACC from the dataset.

cmplCAJC = scCAJC %>% 
           filter(as.numeric(substr(ZIP,1,5))<93000) %>%
           select(UNITID, INSTNM, INSTURL, ZIP, C150_L4, LATITUDE, LONGITUDE, PREDDEG)

nameURL  = paste("<a href='http://",cmplCAJC$INSTURL,"'>",cmplCAJC$INSTNM,"</a>",sep="")
popupText = paste(nameURL, '<BR>',
                  ifelse(cmplCAJC$PREDDEG==1,"Predominant Degree Awarded: Certificate",
                         "Predominant Degree Awarded: Associate's"), '<BR>',
                  'Completion Rate:',
                  as.character(cmplCAJC$C150_L4*100),'%',
                  sep="")

```

```{r showDate, echo=FALSE, comment="", eval=FALSE}
format(Sys.time(),"%B %d, %Y")

```

```{r leaflet, echo=FALSE, warning=FALSE}

# reference: http://rstudio.github.io/leaflet/

library(leaflet)

# placing a marker for a location
# lat: NS; lng: EW

latLA = 34.0522; lngLA = -118.2437
binpal = colorBin(c("tomato","dodgerblue"),cmplCAJC$PREDDEG,2,pretty=FALSE)


CAJC_map = cmplCAJC %>% leaflet() %>% 
   
   setView(lat = latLA, # the lat of the center of the map
           lng = lngLA, # the lng of the center of the map
           zoom=11) %>%

   #addTiles() %>%
   #addProviderTiles(providers$Stamen.Toner) %>%
   
   #addProviderTiles(providers$CartoDB.Positron) %>% 
   addProviderTiles((providers$Esri.NatGeoWorldMap)) %>%
   
   addCircles(
              lat = cmplCAJC$LATITUDE,
              lng = cmplCAJC$LONGITUDE,
              weight = 1,
              #radius = (cmplCAJC$C150_L4) *100*10,
              radius = 1000,
              color = binpal(cmplCAJC$PREDDEG),
              popup = popupText
             ) 
   
   # addPopups(lat=cmplCAJC$LATITUDE,
   #           lng=cmplCAJC$LONGITUDE,
   #           popupText,
   #           options=popupOptions(closeButton=FALSE))
   # 
   
CAJC_map



```